version: '3.8'

services:
  api-parc1:
    build:
      context: ./api-parc1
      dockerfile: Dockerfile
    container_name: api_parc1
    ports:
      - "3001:3000"
    environment:
      - NODE_ENV=production
      - DB_HOST=postgres1
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=your_secure_password
      - DB_NAME=jurassic_db1
    volumes:
      - shared-volume:/app/shared_data
    depends_on:
      - postgres1
    networks:
      - parc-net

  api-parc2:
    build:
      context: ./api-parc2
      dockerfile: Dockerfile
    container_name: api_parc2
    ports:
      - "3002:3000"
    environment:
      - NODE_ENV=production
      - DB_HOST=postgres2
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=password
      - DB_NAME=jurassic_db2
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    volumes:
      - shared-volume:/app/shared_data
    depends_on:
      - postgres2
      - redis
    networks:
      - parc-net

  postgres1:
    image: postgres:14
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=jurassic_db2
    volumes:
      - pgdata1:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    networks:
      - parc-net

  postgres2:
    image: postgres:14
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=jurassic_db2
    volumes:
      - pgdata2:/var/lib/postgresql/data
    ports:
      - "5434:5432"
    networks:
      - parc-net

  redis:
    image: redis:7
    ports:
      - "6379:6379"
    volumes:
      - redisdata:/data
    networks:
      - parc-net

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api-parc1
      - api-parc2
    networks:
      - parc-net

volumes:
  shared-volume:
  pgdata1:
  pgdata2:
  redisdata:

networks:
  parc-net:
    driver: bridge