version: '3.8'

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ton_mdp_postgres
      POSTGRES_DB: parc2
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  api:
    build: .
    ports:
      - "3002:3002"
    environment:
      DATABASE_URL: postgres://postgres:ton_mdp_postgres@db:5432/parc2
    depends_on:
      - db

volumes:
  pgdata:
