version: '3.9'

services:
  postgres2:
    image: postgres:15
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=jurassic_db2
    ports:
      - "5434:5432"
    volumes:
      - pgdata2:/var/lib/postgresql/data

  api:
    build: src
    restart: on-failure
    depends_on:
      - postgres2
      - redis
    ports:
      - "3002:3000"
    env_file:
      - .env

  redis:
    image: redis:alpine
    restart: always
    ports:
      - "6379:6379"

volumes:
  pgdata2:
